-- 2020-12-31 DBMS_09. ERD   ®œcherryuki(ji)

-- ºÓ«Œ∏Ù ERD ø¨Ω¿πÆ¡¶(ºÓ«Œ∏Ù ¡÷πÆº≠∏¶ ∫∏∞Ì DBº≥∞Ë)
-- 201231_ordersheet.exerd (201231_ordersheet.jpg) ¬¸∞Ì
DROP TABLE CUSTOMER;
DROP TABLE PRODUCT;

CREATE TABLE CUSTOMER(
    ID      VARCHAR2(30)    PRIMARY KEY,
    PW      VARCHAR2(30)    NOT NULL,
    CNAME   VARCHAR2(50)    NOT NULL,
    CADDRESS    VARCHAR2(255),
    CTEL    VARCHAR2(50)    UNIQUE,
    CEMAIL  VARCHAR2(40)    UNIQUE  NOT NULL
    );
DESC CUSTOMER;
CREATE TABLE PRODUCT(
    PCODE   VARCHAR2(10)    PRIMARY KEY,
    PNAME   VARCHAR2(50),
    UNIT_PRICE  NUMBER(10),
    STOCK       NUMBER(10)
    );
DESC PRODUCT;
CREATE TABLE SHOP_BASKET(
    BNO     NUMBER(10)  PRIMARY KEY, --BNO_SEQ
    ID      VARCHAR2(30)    REFERENCES CUSTOMER(ID),
    PCODE   VARCHAR2(10)    REFERENCES PRODUCT(PCODE),
    BAMOUNT NUMBER(10),
    BPRICE  NUMBER(30)
    );
CREATE SEQUENCE BNO_SEQ
    MAXVALUE 9999999999
    NOCACHE;
DESC SHOP_BASKET;
CREATE TABLE ORDER_CUSTOMER(
    ORDERNO     NUMBER(20)    PRIMARY KEY, --ORDERDATE||O_SEQ
    ID          VARCHAR2(30)    REFERENCES CUSTOMER(ID),
    ORDERDATE   DATE            DEFAULT SYSDATE NOT NULL,
    OADDRESS    VARCHAR2(255),
    OTEL        VARCHAR2(30)
    );
CREATE SEQUENCE O_SEQ
    MAXVALUE 9999999999
    NOCACHE;
DESC ORDER_CUSTOMER;
CREATE TABLE ORDER_PRODUCT(
    OP_NO   NUMBER(10)      PRIMARY KEY, --OP_SEQ
    ORDERNO NUMBER(20)      REFERENCES ORDER_CUSTOMER(ORDERNO),
    PCODE   VARCHAR2(10)    REFERENCES PRODUCT(PCODE),
    OAMOUNT NUMBER(10),
    OPRICE  NUMBER(30)
    );
CREATE SEQUENCE OP_SEQ
    MAXVALUE 9999999999
    NOCACHE;
DESC ORDER_PRODUCT;

SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM SHOP_BASKET;
SELECT * FROM ORDER_CUSTOMER;
SELECT * FROM ORDER_PRODUCT;