-- 2020-12-31 DBMS_08.SEQUENCE   ⓒcherryuki(ji)
-- [VIII] SEQUENCE: 순사번호 생성기, 인위적인 PRIMARY KEY 용도로 많이 사용
-- CREATE SEQUENCE SequenceName;

CREATE SEQUENCE FRIEND_SEQ; --기본값으로 세팅(1부터 시작, +1, 사이클, 캐시)
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9999
    MINVALUE 1
    NOCYCLE
    NOCACHE;
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NO      NUMBER(4)   PRIMARY KEY,
    NAME    VARCHAR2(30)    NOT NULL,
    PHONE   VARCHAR2(20)    UNIQUE, --UNIQUE:유일, NULL허용
    TEL     VARCHAR2(20),
    LAST_MODIFYED   DATE    DEFAULT SYSDATE
    );
INSERT INTO FRIEND(NO, NAME, PHONE) VALUES (FRIEND_SEQ.NEXTVAL, '공유', '010-0000-0000');
INSERT INTO FRIEND(NO, NAME, PHONE, TEL) VALUES (FRIEND_SEQ.NEXTVAL, '공유', NULL, '02-012-0000');
INSERT INTO FRIEND(NO, NAME, PHONE, TEL) VALUES (FRIEND_SEQ.NEXTVAL, '박보검', '010-7777-7777', '02-012-0000');
INSERT INTO FRIEND (NO, NAME, TEL) VALUES (FRIEND_SEQ.NEXTVAL, '손소유', '02-515-5555');
SELECT * FROM FRIEND;
SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 현재(현재까지 생성된 마지막) 시퀀스 값

-- 총 연습문제
DROP TABLE CUS_LEVEL;
CREATE TABLE CUS_LEVEL(
    LEVELNO     NUMBER(3),
    LEVELNAME   VARCHAR2(20) NOT NULL,
    PRIMARY KEY(LEVELNO)
    );
DESC CUS_LEVEL;

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    CNO     NUMBER(4),
    CNAME   VARCHAR2(20) NOT NULL,
    JOINDATE DATE   DEFAULT SYSDATE,
    PHONE   VARCHAR2(30)    UNIQUE,
    POINT   NUMBER(10),
    LEVELNO NUMBER(3),
    PRIMARY KEY(CNO),
    FOREIGN KEY(LEVELNO)    REFERENCES CUS_LEVEL(LEVELNO)
    );
CREATE SEQUENCE CUS_SQ
    MAXVALUE 9999
    NOCYCLE
    NOCACHE;
DESC CUSTOMER;
SELECT * FROM CUSTOMER;

INSERT INTO CUS_LEVEL VALUES (1, 'VVIP');
INSERT INTO CUS_LEVEL VALUES (2, 'VIP');
INSERT INTO CUS_LEVEL VALUES (3, 'NORMAL');
INSERT INTO CUS_LEVEL VALUES (4, 'BLACK');
SELECT * FROM CUS_LEVEL;

INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'KONG YOU', TO_DATE('15/10/10', 'YY/MM/DD'), '010-0000-0000', 500, 1);
INSERT INTO CUSTOMER VALUES (CUS_SQ.NEXTVAL, 'SON SOYOO', TO_DATE('17/05/20', 'YY/MM/DD'), '010-5555-5555', NULL, 2);
SELECT * FROM CUSTOMER;

SELECT CNO, CNAME, TO_CHAR(JOINDATE, 'YYYY-MM-DD') JOINDATE, PHONE, POINT, LEVELNAME 
    FROM CUS_LEVEL L, CUSTOMER C 
    WHERE L.LEVELNO=C.LEVELNO;