-- 2021-01-04 DBMS_11. INDEX   ⓒcherryuki(ji)
-- [XI] 인덱스(INDEX); 빠른 검색을 위해 사용(처리 속도 향상)
SELECT * FROM USER_INDEXES; -- 딕셔너리뷰에 USER(SCOTT)가 소유한 인덱스 정보
-- 테이블 생성시 PRIMARY KEY로 인덱스 자동 생성됨
DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;
SELECT * FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; --1번(28행), 2번(56행)
SELECT TO_CHAR(COUNT(*), '9,999,999') FROM EMP01;
INSERT INTO EMP01 SELECT * FROM EMP01; -- 229,376행
INSERT INTO EMP01 (EMPNO, ENAME, DEPTNO) VALUES (1111, 'KONG', 40);
INSERT INTO EMP01 SELECT * FROM EMP01; -- 약 180만개
DESC EMP01;
SELECT * FROM EMP01 WHERE ENAME='KONG'; --0.055초
SELECT * FROM EMP01 WHERE EMPNO=1111; --0.055초
-- 인덱스 생성 후 조회
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME);
SELECT * FROM EMP01 WHERE ENAME='KONG'; --0.005초
SELECT * FROM EMP01 WHERE EMPNO=1111; --0.047초
SELECT * FROM USER_INDEXES;
DROP TABLE EMP01; -- TABLE 지우면 INDEX도 같이 지워짐

-- 인덱스로 사용한 칼럼값이 변경되면 이를 위한 내부 구조(B*트리)도 함께 수정 됨 - 오라클 서버에 의해 자동 수정
-- 따라서 인덱스가 있는 경우 조회 속도는 빨라지나 DML 명령어(ISNERT, UPDATE, DELETE) 작업시 속도가 느려짐
-- (인덱스)는 조회의 성능을 향상시키는 객체