-- 21-01-08 JDBC_Dao&Dto 	(c)cherryuki(ji)

SELECT * FROM TAB;
DROP TABLE STUDENT;
DROP TABLE MAJOR;
CREATE TABLE MAJOR(
    MNO     NUMBER(2)   PRIMARY KEY,
    MNAME   VARCHAR2(50)
    );
DESC MAJOR;
INSERT INTO MAJOR VALUES (1, '빅데이터학');
INSERT INTO MAJOR VALUES (2, '경영정보학');
INSERT INTO MAJOR VALUES (3, '컴퓨터공학');
INSERT INTO MAJOR VALUES (4, '소프트웨어');
INSERT INTO MAJOR VALUES (5, '연극영화학');
INSERT INTO MAJOR VALUES (6, '정보전자학');
COMMIT;
SELECT * FROM MAJOR;
CREATE TABLE STUDENT(
    SNO     NUMBER(7)   PRIMARY KEY, -- YEAR||S_SEQ
    SNAME   VARCHAR(30) NOT NULL,
    MNO     NUMBER(2)   REFERENCES MAJOR(MNO),
    SCORE   NUMBER(3)   DEFAULT 0 CHECK(SCORE BETWEEN 0 AND 100),
    SEXPEL  NUMBER(1)   DEFAULT 0 CHECK(SEXPEL IN (0,1))
    );
DESC STUDENT;
DROP SEQUENCE S_SEQ;
CREATE SEQUENCE S_SEQ
    MAXVALUE 999
    NOCYCLE
    NOCACHE;
SELECT * FROM STUDENT;
-- 학번(SNO) 생성 SQL문
SELECT TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')) SNO FROM DUAL;
SELECT EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')) SNO FROM DUAL;
SELECT TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000'))) SNO FROM DUAL;

-- 1) INSERT (이름, 전공명, 점수 입력받아 학생 추가)
--  학번은 현재년도||순차번호(시퀀스 이용)
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')), 
                                '정우성', (SELECT MNO FROM MAJOR WHERE MNAME='빅데이터학'), 90, 0);
INSERT INTO STUDENT VALUES (EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')), 
                                '박세영', (SELECT MNO FROM MAJOR WHERE MNAME='빅데이터학'), 80, 1);
INSERT INTO STUDENT (SNO, SNAME, MNO, SCORE) 
    VALUES (TO_NUMBER(TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000'))),
                '배수지', (SELECT MNO FROM MAJOR WHERE MNAME='컴퓨터공학'), 20);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')), 
                                '홍길동', (SELECT MNO FROM MAJOR WHERE MNAME='소프트웨어'), 95, 0);
INSERT INTO STUDENT VALUES (TO_CHAR(SYSDATE, 'YYYY')||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')), 
                                '송혜교', (SELECT MNO FROM MAJOR WHERE MNAME='연극영화학'), 100, 0);
INSERT INTO STUDENT VALUES (EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(S_SEQ.NEXTVAL, '000')), 
                                '홍철수', (SELECT MNO FROM MAJOR WHERE MNAME='소프트웨어'), 80, 1);
SELECT * FROM STUDENT;
COMMIT;

-- 2) 학과별 조회(학과 이름 입력 받음)
-- 제적당하지 않은 학생만, 점수 높은 순으로 등수, 이름(학번), 학과, 점수 출력
SELECT ROWNUM||'등' RANK, SM.*
    FROM (SELECT SNAME||'('||SNO||')' NAME, MNAME, SCORE FROM STUDENT S, MAJOR M
            WHERE S.MNO=M.MNO AND SEXPEL=0 AND MNAME='빅데이터학'
            ORDER BY SCORE DESC) SM;

-- 3) 학생 전체 조회
SELECT ROWNUM||'등' RANK, SM.*
    FROM (SELECT SNAME||'('||SNO||')' NAME, MNAME, SCORE FROM STUDENT S, MAJOR M
            WHERE S.MNO=M.MNO AND SEXPEL=0
            ORDER BY SCORE DESC) SM;

-- 4) 제적자 전체 조회
SELECT ROWNUM||'등' RANK, SM.*
    FROM (SELECT SNAME||'('||SNO||')' NAME, MNAME, SCORE FROM STUDENT S, MAJOR M
            WHERE S.MNO=M.MNO AND SEXPEL=1
            ORDER BY SCORE DESC) SM;