-- 2021-02-09 RJDBC      ¨Ïcherryuki(ji)
SELECT * FROM DEPT;
INSERT INTO DEPT VALUES (60, 'MARKETING', 'TOKYO');
UPDATE DEPT SET LOC='SEOUL KOREA' WHERE DEPTNO=50;
DELETE DEPT WHERE DEPTNO>40;
ROLLBACK;